export const USER_ADD_DATA = [
  { name: '한줄소개', placeHolder: '한 줄 소개', type: 'text', dataName: 'userIntro' },
  { name: '성별', options: ['남자', '여자'], type: 'radio', dataName: 'gender' },
  { name: '나이', options: ['10대', '20대', '30대 이상'], type: 'radio', dataName: 'age' },
  { name: '선호 지역', options: ['강남', '건대', '홍대'], type: 'radio', dataName: 'preferenceLocation' },
  {
    name: 'MBTI',
    options: [
      '선택',
      'ISTJ',
      'ISFJ',
      'INFJ',
      'INTJ',
      'ISTP',
      'ISFP',
      'INFP',
      'INTP',
      'ESTP',
      'ESFP',
      'ENFP',
      'ENTP',
      'ESTJ',
      'ESFJ',
      'ENFJ',
      'ENTJ',
    ],
    type: 'select',
    dataName: 'mbti',
  },
  {
    name: '선호 테마',
    options: [
      '없음',
      '추리',
      '미스테리',
      '공포',
      '판타지',
      'SF',
      '모험',
      '로맨스',
      '드라마',
      '감성',
      '범죄',
      '스릴러',
      '액션',
      '19금',
    ],
    type: 'select',
    dataName: 'preferenceTheme',
  },
  {
    name: '비선호 테마',
    options: [
      '없음',
      '추리',
      '미스테리',
      '공포',
      '판타지',
      'SF',
      '모험',
      '로맨스',
      '드라마',
      '감성',
      '범죄',
      '스릴러',
      '액션',
      '19금',
    ],
    type: 'select',
    dataName: 'nonPreferenceTheme',
  },
];
